version: 0.2

# CodeBuild - Build & Push Docker Image to ECR
# Security Scan Pipeline - Tech Talks UG Malang

env:
  variables:
    AWS_REGION: "ap-southeast-1"
    ECR_REPO_NAME: "aws-ug-demo-ecr"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - BUILD_DATE=$(date +%Y%m%d)
      - IMAGE_TAG="aws-ug-demo-image-${BUILD_DATE}"
      - echo "Image tag - $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Build completed - image ready for Inspector scan"

artifacts:
  files:
    - "**/*"
  discard-paths: no
