version: 0.2

# CodeBuild - SAST dengan Amazon Inspector SBOM Generator
# Security Scan Pipeline - Tech Talks UG Malang

env:
  variables:
    AWS_REGION: "ap-southeast-1"

phases:
  install:
    commands:
      - echo "Installing Amazon Inspector SBOM Generator..."
      # Download inspector-sbomgen dengan URL yang benar
      - |
        SBOMGEN_URL="https://amazon-inspector-sbomgen.s3.amazonaws.com/latest/linux/amd64/inspector-sbomgen"
        curl -fsSL -o inspector-sbomgen "$SBOMGEN_URL"
        
        # Validasi download berhasil (bukan XML error)
        if file inspector-sbomgen | grep -q "executable"; then
          echo "Download successful - valid binary"
          chmod +x inspector-sbomgen
          mv inspector-sbomgen /usr/local/bin/
          inspector-sbomgen --version
        else
          echo "Download failed or invalid file. Trying alternative method..."
          # Alternative: download via AWS CLI dari S3
          aws s3 cp s3://amazon-inspector-sbomgen/latest/linux/amd64/inspector-sbomgen ./inspector-sbomgen --region us-east-1
          chmod +x inspector-sbomgen
          mv inspector-sbomgen /usr/local/bin/
          inspector-sbomgen --version
        fi

  pre_build:
    commands:
      - echo "Starting SAST scan with Amazon Inspector..."
      - echo "Scan ID - $CODEBUILD_BUILD_ID"

  build:
    commands:
      - echo "Generating SBOM from source code..."
      # Generate SBOM dari source code
      - |
        inspector-sbomgen directory \
          --path . \
          --outfile sbom.json \
          --scanners programming-language-packages
        
        # Validasi SBOM generated
        if [ -f sbom.json ]; then
          echo "SBOM generated successfully"
          echo "SBOM size: $(wc -c < sbom.json) bytes"
        else
          echo "ERROR: SBOM generation failed!"
          exit 1
        fi
        
      # Scan SBOM dengan Inspector Scan API
      - echo "Scanning SBOM with Amazon Inspector..."
      - |
        aws inspector-scan scan-sbom \
          --sbom file://sbom.json \
          --output-format INSPECTOR > inspector-sast-findings.json
        
        cat inspector-sast-findings.json
        
        # Count findings by severity
        CRITICAL=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "critical")] | length // 0')
        HIGH=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "high")] | length // 0')
        MEDIUM=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "medium")] | length // 0')
        LOW=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "low")] | length // 0')
        
        echo "========================================"
        echo "=== Inspector SAST Scan Summary ==="
        echo "========================================"
        echo "Critical: $CRITICAL"
        echo "High: $HIGH"
        echo "Medium: $MEDIUM"
        echo "Low: $LOW"
        echo "========================================"
        
        # Fail build jika ada critical vulnerabilities
        # Uncomment untuk enforce security gate
        # if [ "$CRITICAL" -gt 0 ]; then
        #   echo "CRITICAL vulnerabilities found! Failing build."
        #   exit 1
        # fi

  post_build:
    commands:
      - echo "SAST scan completed"
      - echo "Proceed to Docker build stage"

artifacts:
  files:
    - sbom.json
    - inspector-sast-findings.json
  discard-paths: yes
