version: 0.2

# CodeBuild - SAST dengan Amazon Inspector SBOM Generator
# Security Scan Pipeline - Tech Talks UG Malang

env:
  variables:
    AWS_REGION: "ap-southeast-1"

phases:
  install:
    commands:
      - echo "Installing Amazon Inspector SBOM Generator..."
      # Download dengan verbose untuk debug
      - |
        echo "Downloading inspector-sbomgen..."
        curl -v -L -o inspector-sbomgen.zip "https://amazon-inspector-sbomgen.s3.amazonaws.com/latest/linux/amd64/inspector-sbomgen.zip" 2>&1 | tail -20
        
        echo "Download complete. File info:"
        ls -la inspector-sbomgen.zip || echo "File not found"
        file inspector-sbomgen.zip || echo "Cannot check file type"
        
        # Coba unzip
        echo "Extracting..."
        unzip -o inspector-sbomgen.zip || { echo "Unzip failed, trying as direct binary..."; mv inspector-sbomgen.zip inspector-sbomgen; }
        
        ls -la
        
        # Find and setup binary
        if [ -f "inspector-sbomgen" ]; then
          chmod +x inspector-sbomgen
          ./inspector-sbomgen --version || echo "Direct run failed"
          mv inspector-sbomgen /usr/local/bin/
        elif [ -d "inspector-sbomgen" ]; then
          chmod +x inspector-sbomgen/inspector-sbomgen
          ./inspector-sbomgen/inspector-sbomgen --version
          mv inspector-sbomgen/inspector-sbomgen /usr/local/bin/
        else
          echo "Looking for binary in extracted files..."
          find . -name "inspector-sbomgen" -type f
          BINARY=$(find . -name "inspector-sbomgen" -type f | head -1)
          if [ -n "$BINARY" ]; then
            chmod +x "$BINARY"
            mv "$BINARY" /usr/local/bin/
          else
            echo "ERROR: Could not find inspector-sbomgen binary"
            exit 1
          fi
        fi
        
        echo "Verifying installation..."
        which inspector-sbomgen
        inspector-sbomgen --version

  pre_build:
    commands:
      - echo "Starting SAST scan with Amazon Inspector..."
      - echo "Scan ID - $CODEBUILD_BUILD_ID"

  build:
    commands:
      - echo "Generating SBOM from source code..."
      - |
        inspector-sbomgen directory \
          --path . \
          --outfile sbom.json \
          --scanners programming-language-packages
        
        if [ -f sbom.json ]; then
          echo "SBOM generated successfully"
          echo "SBOM size: $(wc -c < sbom.json) bytes"
        else
          echo "ERROR: SBOM generation failed!"
          exit 1
        fi
        
      - echo "Scanning SBOM with Amazon Inspector..."
      - |
        aws inspector-scan scan-sbom \
          --sbom file://sbom.json \
          --output-format INSPECTOR > inspector-sast-findings.json
        
        cat inspector-sast-findings.json
        
        CRITICAL=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "critical")] | length // 0')
        HIGH=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "high")] | length // 0')
        MEDIUM=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "medium")] | length // 0')
        LOW=$(cat inspector-sast-findings.json | jq '[.sbom.vulnerabilities[]? | select(.severity == "low")] | length // 0')
        
        echo "========================================"
        echo "=== Inspector SAST Scan Summary ==="
        echo "========================================"
        echo "Critical: $CRITICAL"
        echo "High: $HIGH"
        echo "Medium: $MEDIUM"
        echo "Low: $LOW"
        echo "========================================"

  post_build:
    commands:
      - echo "SAST scan completed"

artifacts:
  files:
    - sbom.json
    - inspector-sast-findings.json
  discard-paths: yes
